### ISSUE TITLE
问一下数据库连接在哪一步

### ISSUE THREAD

**Issue by 13637064637** [sqrtcat/easy-gin#1]
问一下，mysql的连接在哪一步，mysql.go的init方法什么时候调用的

**Comment by sqrtcat** [comment]
> 问一下，mysql的连接在哪一步，mysql.go的init方法什么时候调用的

在包 "easy-gin/drivers" 初次被载入时会触发调用 init 方法（go 的基本特性，当包被初次载入时，会执行包内所有的 init 方法），我现在放在 main.go 中
